name: Build Tokenizers for armv8l

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake rustc cargo pkg-config
        
    - name: Build tokenizers from source for armv8-a
      run: |
        mkdir -p wheels
        pip install --upgrade pip wheel setuptools
        git clone https://github.com/huggingface/tokenizers
        cd tokenizers/bindings/python
        export CFLAGS="-march=armv8-a"
        export CXXFLAGS="-march=armv8-a"
        pip wheel . --wheel-dir=../../../wheels/
    
    - name: Rename wheel
      run: |
        cd wheels
        for file in tokenizers-*.whl; do
          newname=$(echo $file | sed 's/aarch64/armv8l/g')
          mv "$file" "$newname"
        done
    
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: tokenizers-armv8l-wheel
        path: wheels/*.whl
